version: "3.9"

services:
  ###
  # iSantePlus Server
  ###
  isanteplus:
    container_name: isanteplus
    hostname: isanteplus
    image: ghcr.io/isanteplus/docker-isanteplus-server:${ISANTEPLUS_DOCKER_VERSION}
    restart: unless-stopped
    env_file:
      - ./isanteplus.env
    volumes:
      - /openmrs/data
      - ./custom_modules:/custom_modules
      - ./dist:/openmrs/data/frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
    - "8080:8080"
    - "1044:1044"

  isanteplus-mysql:
    image: ghcr.io/isanteplus/docker-isanteplus-db:${ISANTEPLUS_DB_VERSION}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=""
    restart: unless-stopped
    container_name: isanteplus-mysql
    hostname: isanteplus-mysql
    healthcheck:
      test: "exit 0"
    environment:
      - MYSQL_DATABASE=openmrs
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_ROOT_HOST=% # Allow docker containers to connect to mysql
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf # mysql config preconfigured to allow binlog/debezium
      - /var/lib/mysql
    ports:
    - "3306:3306"
